"""
Django settings for accpre project.

Generated by 'django-admin startproject' using Django 3.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/ Articles
"""

from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent
SECRET_KEY = 'django-insecure-lb^yn@#k(+fnf!2k^(99h9xy@@l+vur-*4zclm73$9lh(&bb^n'
DEBUG = True
ALLOWED_HOSTS = []

# 用户认证
CLIENT_ID = "WJ6rAkO4r0iKWtsm2dtmFVySlxHccIt90M47uWO4"
CLIENT_SECRET = "pe843MRWfCylspXhveCygCMuzAcInpQboQf6a8PRp03Bg7DMTZQe"

# 超级管理员账号：admin
# 明文密码：admin123
# 密文：pbkdf2_sha256$260000$bC92BKCzTNtUSfuSSJadwz$5s9b6dZASJvmmQ9NU7OGabA1cQCjUjnGNWRR06mU0KY =

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'blogs.apps.BlogsConfig',
    'users.apps.UsersConfig',
    'rest_framework',
    'oauth2_provider',
    'corsheaders',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # 跨域
]
CORS_ORIGIN_ALLOW_ALL = True
ROOT_URLCONF = 'accpre.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'accpre.wsgi.application'
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'accpre',
        'USER': 'root',
        'PASSWORD': 'xxx',
        'HOST': 'xxx',
        'PORT': 'xxx'
    }
}

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'accpre.core.permissions.AccPreIsAuthenticated'
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': (
        "oauth2_provider.contrib.rest_framework.OAuth2Authentication",
    )
}

# token 过期时间
OAUTH2_PROVIDER = {
    'ACCESS_TOKEN_EXPIRE_SECONDS': 60 * 60 * 24 * 30

}

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Asia/Shanghai'
USE_I18N = True
USE_L10N = True
USE_TZ = False

STATIC_URL = '/static/'
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

USER_ROLE_SUPER = 1
USER_ROLE_MANAGEMENT = 2
USER_ROLE_COMMON = 3


USER_ROLE_CHOICES = (
    (USER_ROLE_SUPER, 'super'),
    (USER_ROLE_MANAGEMENT, 'management'),
    (USER_ROLE_COMMON, 'common')
)

DEFAULT_OAUTH_TOKEN_URL = '/oauth/token/'
DEFAULT_OAUTH_TOKEN_REQUEST_METHOD = 'POST'
DEFAULT_OAUTH_TOKEN_BODY = "username={username}" \
                           "&password={password}" \
                           "&grant_type=password" \
                           "&client_id={client_id}" \
                           "&client_secret={client_secret}"
DEFAULT_VARCHAR_LENGTH = 20
CERTIFICATION_PASS_LIST = [
    '/login/',  # 登录
]
